text="KQEREJEBCPPCJCRKIEACUZBKRVPKRBCIBQCARBJCVFCUPKRIOFKPACUZQEPBKRXPEIIEAABDKPBCPFCDCCAFIEABDKPBCPFEQPKAZBKRHAIBKAPCCIBURCCDKDCCJCIDFUIXPAFFERBICZDFKABICBBENEFCUPJCVKABPCYDCCDPKBCOCPERKIVKSCPICBRKIJPKABI"
'''dict={}
for i in text:
	if i in dict:
		dict[i]=dict[i]+1
	else:
		dict[i]=1
print (dict)'''
ans=""
for i in text:
	temp=((ord(i)-65-4)*11)%26
	ans=ans+chr(temp+65)
print (ans)